[package]
name = "cw-orch-interchain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-recursion = "1.0.4"
base64 = "0.21.2"
cosmwasm-schema = "1.3.1"
futures = "0.3.28"
ibc-chain-registry = "0.25.0"
ibc-relayer-types = "0.25.0"
log = "0.4.19"
log4rs = "1.2.0"
thiserror = "1.0.44"
tokio = "1.29.1"
tonic = "0.9.2"
cw-orch-starship = {path="../cw-orch-starship"}
