[package]
authors.workspace    = true
description          = "Adapter for interacting with ibc on cw-multi-test via cw-orch"
edition.workspace    = true
license.workspace    = true
name                 = "cw-orch-interchain-mock"
repository.workspace = true
version              = "0.9.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-core = { workspace = true }
cw-orch-mock = { workspace = true }

anyhow                  = { workspace = true }
cosmrs                  = { workspace = true }
cosmwasm-std            = { workspace = true }
cw-orch-interchain-core = { workspace = true }
cw-utils                = { workspace = true }
ibc-relayer-types       = { workspace = true }
log                     = { workspace = true }
serde                   = { workspace = true }
serde_json              = { workspace = true }
thiserror               = { workspace = true }

[dev-dependencies]
cw20 = { workspace = true }
